---
title: "Flexdashboard_lab_ps3"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bootswatch: minty
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(scales)
library(ggforce)
library(ggrepel)
library(gghighlight)
library(ggplot2)
library(dplyr)
library(forcats)
library(maps)
library(scales)
library(colorblindr)
library(patchwork)
library(plotly) # adds some interactivity to the plot
theme_set(theme_minimal(base_family = "Times"))
```

```{r include=FALSE}
honey <- read.csv(here("data","honeyproduction.csv"))
```

Honey stock and values {.sidebar}
===============
Here are some fun facts about the honey industry in the United States. Check out the [honey](https://honey.com/newsroom/presskit/honey-industry-facts)

# Honey Stocks and Product Value by States

Column {.tabset}
-----------------------------------------------------------------------
### Chart A
```{r include=FALSE}
honey_98_12 <- honey %>% 
  filter(year == 1998 | year == 2012) %>% 
  select(state, year, stocks) %>% 
  mutate(state = fct_reorder(state, stocks))

p1 <- ggplot(honey_98_12, aes(x = state, y = stocks, fill = year)) +
  geom_col(position = "dodge") +
  labs(title = "Honey Stocks by State in 1998 vs 2012",
       x = "State",
       y = "Honey Stocks",
       fill = "Year") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 5))+
  scale_y_continuous(labels = label_comma())
```

```{r}
ggplotly(p1)
```

### Chart B

```{r include=FALSE}
honey_2012 <- honey %>% 
  filter(year == 2012)

honey_2012 <- honey_2012 %>% 
  mutate(state = tolower(state.name[match(state, state.abb)]))

us_states <- map_data("state")

map_data_merged <- us_states %>% 
  left_join(honey_2012, by = c("region" = "state"))

p2 <- ggplot(map_data_merged, aes(x = long, y = lat, group = group, fill = prodvalue)) +
  geom_polygon(color = "white") +
  scale_fill_viridis_c(option = "plasma", na.value = "grey90") +
  scale_fill_continuous(name = "Production Value", labels = label_dollar()) +
  labs(title = "Honey Production Value by State(2012)",
       x = "Longitude",
       y = "Latitude",
       fill = "Production Value ($)")
```


```{r}
ggplotly(p2)
```

### Chart C

```{r}
p1/p2 + plot_layout(guides = "collect", heights = c(1,1))
```
